//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by poesie.rc
//
#define ID_NEWWORD                      3
#define ID_EDITWORD                     4
#define ID_DELETEWORD                   5
#define ID_LEXBOX                       7
#define ID_IMPORT                       8
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_POESIE_DIALOG               102
#define IDD_OPTIONS_DIALOG              103
#define IDD_DICTIONARY_DIALOG           104
#define IDD_WORD_DIALOG                 105
#define IDD_IPA_DIALOG                  105
#define IDD_SILBE_PHONE_DIALOG          106
#define IDD_PHONEBOX                    107
#define IDD_SILBE_DIALOG                108
#define IDD_WRD_DIALOG                  110
#define IDD_IMPORT_DIALOG               111
#define IDD_SYNTAX_DIALOG               112
#define IDD_WORDNET_DIALOG              113
#define IDD_POS_DIALOG                  114
#define IDD_IPAPOEM_DIALOG              115
#define IDD_WORMOPTIONS_DIALOG          116
#define IDR_MAINFRAME                   128
#define IDB_BITMAP6                     134
#define IDB_DICTIONARY                  136
#define IDB_WORDNET                     142
#define IDB_COMMON                      144
#define IDB_SYNTAX                      148
#define IDB_IPATRANS                    149
#define IDB_IGFH                        151
#define IDB_EXCEPTION                   152
#define IDB_COMPILER                    153
#define ID_CONTINUE                     1001
#define ID_NEWPOEM                      1002
#define ID_OPTIONS                      1003
#define ID_MAKEPOEM                     1004
#define IDC_HASTITLE                    1005
#define IDC_POEMFORM                    1006
#define IDC_NUMSTANZAS                  1007
#define IDC_NUMVERSE                    1008
#define IDC_STANZALENGTH                1009
#define IDC_POEM                        1010
#define IDC_HASTITLE2                   1010
#define IDC_REIMTYPE                    1011
#define IDC_ST_STANZAS                  1012
#define IDC_ST_VERSES                   1013
#define ID_DICTIONARY                   1014
#define IDC_COMPILER                    1014
#define IDC_WORDLIST                    1015
#define ID_ABOUT                        1015
#define IDC_EDIT1                       1016
#define IDC_WORDTEXT                    1016
#define IDC_BREAKDISPLAY                1016
#define ID_REPAIR                       1016
#define IDC_ROOTWORD                    1016
#define IDC_SYNTAGMA_INDEX              1016
#define ID_SILBE1                       1017
#define ID_WORDNET                      1017
#define ID_SILBE2                       1018
#define ID_SYNTAX                       1018
#define ID_SILBE3                       1019
#define ID_IPATRANS                     1019
#define ID_SILBE4                       1020
#define ID_CMUIMPORT                    1020
#define ID_SILBE5                       1021
#define ID_READ                         1021
#define IDC_NUMSILBEN                   1022
#define ID_IPAPOEM                      1022
#define IDC_EDIT2                       1023
#define IDC_EXTRATEXT                   1023
#define IDC_SYNTAGMA_EDIT               1023
#define ID_SAVEAS                       1023
#define IDC_PHONETEXT                   1024
#define ID_SILBE6                       1025
#define ID_SILBE7                       1027
#define ID_SILBE8                       1028
#define ID_SILBE9                       1029
#define ID_SILBE10                      1030
#define ID_SILBE11                      1031
#define ID_SILBE12                      1032
#define ID_SILBE13                      1033
#define ID_SILBE14                      1034
#define ID_SILBE15                      1035
#define ID_SILBE16                      1036
#define ID_SILBE17                      1037
#define ID_SILBE18                      1038
#define ID_SILBE19                      1039
#define ID_SILBE20                      1040
#define ID_SILBE21                      1041
#define ID_SILBE22                      1042
#define ID_SILBE23                      1043
#define ID_SILBE24                      1044
#define ID_SILBE25                      1045
#define ID_SILBE26                      1046
#define ID_SILBE27                      1047
#define ID_SILBE28                      1048
#define ID_SILBE29                      1049
#define ID_SILBE30                      1050
#define ID_SILBE31                      1051
#define ID_SILBE32                      1052
#define ID_SILBE33                      1053
#define ID_SILBE34                      1054
#define ID_SILBE35                      1055
#define ID_SILBE36                      1056
#define ID_SILBE37                      1057
#define IDC_TONE                        1058
#define ID_SILBE39                      1059
#define ID_SILBE40                      1060
#define ID_SILBE41                      1061
#define ID_SILBE42                      1062
#define ID_SILBE43                      1063
#define ID_SILBE44                      1064
#define ID_SILBE45                      1065
#define ID_SILBE46                      1066
#define ID_SILBE47                      1067
#define ID_SILBE48                      1068
#define ID_SILBE49                      1069
#define ID_SILBE50                      1070
#define ID_SILBE51                      1071
#define ID_SILBE52                      1072
#define ID_SILBE53                      1073
#define ID_SILBE54                      1074
#define ID_SILBE55                      1075
#define ID_SILBE56                      1076
#define IDC_FLEXIBLE                    1077
#define ID_SILBE58                      1078
#define ID_SILBE57                      1079
#define ID_SILBE59                      1080
#define IDC_SILBEFILTER                 1081
#define IDC_AMBIG                       1082
#define IDC_HIDDEN                      1083
#define IDC_WORDTYPE                    1084
#define IDC_WORDCODE                    1085
#define IDC_GENDER                      1086
#define ID_PHONEBOX                     1087
#define IDC_PLURAL                      1088
#define IDC_PHONEDISPLAY                1089
#define IDC_TAKESAN                     1089
#define ST_GENDER                       1090
#define ID_SILBE_PHONE                  1091
#define ST_LEXENTRY                     1094
#define ST_WORDBODY                     1095
#define ST_WORDTYPE                     1096
#define IDC_BREAKGROUP                  1100
#define IDC_BREAKPLUS                   1101
#define IDC_BREAKMINUS                  1103
#define IDC_CMUMESSAGE                  1105
#define ID_COMMONIMPORT                 1107
#define ID_GENERATE                     1107
#define ID_SEM_SHOW                     1108
#define ID_EXCIMPORT                    1108
#define IDC_COREMESSAGE                 1109
#define ID_FILEFIND                     1109
#define IDC_WORDNETRESULT               1110
#define IDC_EXCMESSAGE                  1110
#define IDC_SYN_FILENAME                1110
#define IDC_POS_WORD                    1111
#define IDC_SYN_N                       1112
#define IDC_SYN_NP                      1113
#define IDC_SYN_V                       1114
#define IDC_SYN_VS                      1115
#define IDC_SYN_VG                      1116
#define IDC_SYN_VA                      1117
#define IDC_SYN_VP                      1118
#define IDC_SYN_A                       1119
#define IDC_SYN_AC                      1120
#define IDC_SYN_AS                      1121
#define IDC_SYN_R                       1122
#define IDC_POS_SYNTAG                  1123
#define IDC_SYNTAGMA_CHG                1125
#define IDC_SYN_TITLES                  1129
#define IDC_IPAPOEM                     1130
#define ID_COMPILEROPTS                 1131

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1132
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
